const express = require('express')
const app = express()
app.use(express.json())
const cors = require('cors')
app.use(cors())

const prisma = require('./src/prismaClient')

const userRoutes = require('./src/routes/userRoutes')
const blPlayerRoutes = require('./src/routes/blPlayerRoutes')
const questions = require('./src/routes/questionRoutes')
const responses = require('./src/routes/responseRoutes')
const complete = require('./src/routes/completeRoutes')
app.use(userRoutes)
app.use(blPlayerRoutes)
app.use(questions)
app.use(responses)
app.use(complete)

app.listen(3001, '0.0.0.0', () => {console.log("Server started on 3001")})