const express = require('express')
const app = express()
app.use(express.json())
const cors = require('cors')
app.use(cors())

const prisma = require('./prismaClient')

const userRoutes = require('./routes/userRoutes')
const blPlayerRoutes = require('./routes/blPlayerRoutes')
const questions = require('./routes/questionRoutes')
const responses = require('./routes/responseRoutes')
const complete = require('./routes/completeRoutes')
app.use(userRoutes)
app.use(blPlayerRoutes)
app.use(questions)
app.use(responses)
app.use(complete)

app.listen(3001, () => {console.log("Server started on 3001")})