-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "favBLPlayer" TEXT,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BLPlayer" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "birthDate" TEXT NOT NULL,
    "zodiac" TEXT NOT NULL,
    "birthPlace" TEXT NOT NULL,
    "family" TEXT NOT NULL,
    "height" DOUBLE PRECISION NOT NULL,
    "shoeSize" INTEGER NOT NULL,
    "vision" DOUBLE PRECISION NOT NULL,
    "bloodType" TEXT NOT NULL,
    "proTeam" TEXT NOT NULL,
    "domLeg" TEXT NOT NULL,
    "favPlayer" TEXT NOT NULL,
    "startAge" TEXT NOT NULL,
    "motto" TEXT NOT NULL,
    "nickname" TEXT NOT NULL,
    "quality" TEXT NOT NULL,
    "defect" TEXT NOT NULL,
    "favFood" TEXT NOT NULL,
    "hateFood" TEXT NOT NULL,
    "riceSideDish" TEXT NOT NULL,
    "hobbies" TEXT NOT NULL,
    "favSeason" TEXT NOT NULL,
    "favStrong" TEXT NOT NULL,
    "favMovie" TEXT NOT NULL,
    "favColor" TEXT NOT NULL,
    "favFamous" TEXT NOT NULL,
    "favAnimal" TEXT NOT NULL,
    "favSubject" TEXT NOT NULL,
    "hateSubject" TEXT NOT NULL,
    "freqMagazine" TEXT NOT NULL,
    "fetish" TEXT NOT NULL,
    "makesHappy" TEXT NOT NULL,
    "makesSad" TEXT NOT NULL,
    "partnerType" TEXT NOT NULL,
    "firstLoveAge" TEXT NOT NULL,
    "firstConfession" TEXT NOT NULL,
    "valentineChoco" TEXT NOT NULL,
    "sleepTime" TEXT NOT NULL,
    "firstWash" TEXT NOT NULL,
    "alwaysBuy" TEXT NOT NULL,
    "criedRecently" TEXT NOT NULL,
    "disbeliefSanta" TEXT NOT NULL,
    "giftSanta" TEXT NOT NULL,
    "lastDayPlan" TEXT NOT NULL,
    "richPlan" TEXT NOT NULL,
    "weekendPlan" TEXT NOT NULL,
    "altCareer" TEXT NOT NULL,
    "favHistoryChar" TEXT NOT NULL,
    "oneObject" TEXT NOT NULL,
    "timeMachine" TEXT NOT NULL,

    CONSTRAINT "BLPlayer_pkey" PRIMARY KEY ("id")
);
